sudo: required

services:
  - docker

before_script: env | grep TRAVIS_

script: 'make test'

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then
      docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD;
      make push;
    fi
